### ISSUE TITLE
[Bug] One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by justin-tsai** [firebase/firebase-unity-sdk#1128]
### Description

When I build my project without development mode, it builds fine, but when I toggle on development and build, the app crashes before the splash screen with the following logs below.

### Reproducing the issue

1. Target Android platform
2. Add components below
3. Set script backend to IL2CPP and enable ARM64 Target Architecture
4. Set Minimum API Level to 24 and Target API Level to 35
5. Enable development build in the build settings
6. Build and run to device

### Firebase Unity SDK Version

11.9.0

### Unity editor version

2022.3.10f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Messaging

### Other Firebase Component(s) in use

App Check, Authentication, Crashlytics, Functions, In-App Messaging, Installations, Messaging, Remote Config

### Additional SDKs you are using

MAX SDK

### Targeted Platform(s)

Android

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### Relevant Log Output

```shell
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime FATAL EXCEPTION: main
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime Process: com.bundle, PID: 4988
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bundle/com.google.firebase.MessagingUnityPlayerActivity}: java.lang.SecurityException: com.bundle: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:106)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.os.Looper.loopOnce(Looper.java:230)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:319)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8919)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime Caused by: java.lang.SecurityException: com.bundle: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.os.Parcel.createException(Parcel.java:3053)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.os.Parcel.readException(Parcel.java:3036)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.os.Parcel.readException(Parcel.java:2978)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6157)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at com.unity3d.player.UnityPlayer.<init>(Unknown Source:331)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at com.unity3d.player.UnityPlayerActivity.onCreate(UnityPlayerActivity.java:40)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at com.google.firebase.MessagingUnityPlayerActivity.onCreate(MessagingUnityPlayerActivity.java:80)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.Activity.performCreate(Activity.java:8975)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.Activity.performCreate(Activity.java:8944)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	... 12 more
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime Caused by: android.os.RemoteException: Remote stack trace:
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16680)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:11613)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2961)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3199)
2024/10/21 16:51:26.786 4988 4988 Error AndroidRuntime 	at android.os.Binder.execTransactInternal(Binder.java:1375)
```

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by justin-tsai** [comment]
I tried upgrading Firebase to v12.3.0 and I still see the same error

**Comment by argzdev** [comment]
Hey @justin-tsai, thanks for reaching out. There were recently some changes made which requires using the latest version of Unity Editor `2022`. I did some testing, using `2022.3.47f1` and [Firebase Unity Quickstart](https://github.com/firebase/quickstart-unity) for Messaging, and so far I'm not encountering this issue. Please also note that you'd need to increase your minimum API Level to 24 in order to use the latest SDK version. That said, I believe this should resolve the issue. Feel free to come back here if you still encounter the issue. Thanks!
