### ISSUE TITLE
Crashlytics - No native stack traces on Java exception

### ISSUE THREAD

**Issue by AntonPetrov83** [firebase/firebase-unity-sdk#141]
Hi!

I am investigating ANRs, so I have included ANR-WatchDog library to throw java.lang.Error when main thread is blocked for more than 5000 ms.

It works but in Crashlytics I can see only Java stacktraces. For example:

```
UnityMain
       at com.unity3d.player.UnityPlayer.nativeRender()
       at com.unity3d.player.UnityPlayer.access$300()
       at com.unity3d.player.UnityPlayer$e$1.handleMessage()
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:203)
       at com.unity3d.player.UnityPlayer$e.run()
```

`nativeRender()` is where all Unity scripts are executed and I expect to see native code there (because of IL2CPP).

What am I doing wrong?

Unity - 2020.3.0f1
Firebase SDK - 8.4.0

**Comment by chkuang-g** [comment]
@AntonPetrov83 

Thank you for reporting this.

Have you tried to upload symbol using these steps?
https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=unity

**Comment by AntonPetrov83** [comment]
@chkuang-g 

> Have you tried to upload symbol using these steps? https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=unity

Yes, I did. Symbolication for ANRs is not supported officially (see [1280](https://github.com/firebase/quickstart-unity/issues/1280))

**Comment by chkuang-g** [comment]
I see.  Let's use https://github.com/firebase/quickstart-unity/issues/1280 to track this FR.
