### ISSUE TITLE
Firebase 8.8.0 Unable to find Method com/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk.getInstance

### ISSUE THREAD

**Issue by soodsaurabh95** [firebase/firebase-unity-sdk#203]
After upgrading to Firebase 8.8.0 in our unity project, I am seeing this error in our Android builds

```
03-16 14:52:59.054  8184  8257 W System.err: java.lang.NoSuchMethodError: no static method "Lcom/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk;.getInstance()Lcom/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk;"
03-16 14:52:59.054  8184  8257 W System.err: 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
03-16 14:52:59.054  8184  8257 W System.err: 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
03-16 14:52:59.054  8184  8257 W System.err: 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
03-16 14:52:59.054  8184  8257 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-16 14:52:59.054  8184  8257 W System.err: 	at android.os.Looper.loopOnce(Looper.java:226)
03-16 14:52:59.054  8184  8257 W System.err: 	at android.os.Looper.loop(Looper.java:313)
03-16 14:52:59.054  8184  8257 W System.err: 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
03-16 14:52:59.054  8184  8257 E firebase: method_ids[i] || (method.optional == kMethodOptional)
03-16 14:52:59.054  8184  8257 E firebase: Unable to find Method com/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk.getInstance (signature '()Lcom/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk;', static).  Please verify the AAR which contains the com/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk class is included in your app.
03-16 14:52:59.058  8184  8257 E Unity   : NullReferenceException: Object reference not set to an instance of an object.
03-16 14:52:59.058  8184  8257 E Unity   :   at Firebase.Crashlytics.Crashlytics.Log (System.String message) [0x00000] in <00000000000000000000000000000000>:0 
```

I have referenced this thread as well https://github.com/firebase/quickstart-unity/issues/1177

I tried changing the version of `com.google.firebase:firebase-crashlytics-ndk:18.2.7` to 18.2.9 but did not work.

**Comment by soodsaurabh95** [comment]
Solved this by adding `-keep class com.google.firebase.** { *; }` to the proguard-user.txt file.
