### ISSUE TITLE
[Bug] Error SQLiteLog (1) table global_log_event_state already exists

### ISSUE THREAD

**Issue by shefich** [firebase/firebase-unity-sdk#324]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.34 f1
  * Firebase Unity SDK version: 8.3.0, 8.6.2, 8.8.0, 8.9.0, 8.10.0, 8.10.1, 9.0.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: ...
  * Other Firebase Components in use: FirebaseAnalytics, FirebaseCrashlytics
  * Additional SDKs you are using: Admob, Onesignal, GPGS
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the https://firebase.google.com/download/unity

### [REQUIRED] Please describe the issue here:
After these logs:
```
2022.06.01 18:14:58.446 2706 2706 Info FirebaseApp Device unlocked: initializing all Firebase APIs for app [DEFAULT]
2022.06.01 18:14:58.448 2706 2706 Info FirebaseCrashlytics Initializing Firebase Crashlytics 18.2.10 for ...
2022.06.01 18:14:58.477 2706 2706 Info FirebaseInitProvider FirebaseApp initialization successful
2022.06.01 18:14:58.484 2706 2706 Debug WM-WrkMgrInitializer Initializing WorkManager with default configuration.
2022.06.01 18:14:58.489 2706 2706 Debug ActivityThread handleBindApplication() --
2022.06.01 18:14:58.502 2706 2805 Info SQLiteOpenHelper DB version upgrading from 4 to 5
```

I can see such crash logs:
```
2022.06.01 18:14:58.522 2706 2805 Error SQLiteLog (1) table global_log_event_state already exists in "CREATE TABLE global_log_event_state (last_metrics_upload_ms BIGINT PRIMARY KEY)"
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor Background execution failure.
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor android.database.sqlite.SQLiteException: table global_log_event_state already exists (code 1 SQLITE_ERROR[1]): , while compiling: CREATE TABLE global_log_event_state (last_metrics_upload_ms BIGINT PRIMARY KEY)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1478)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:916)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2462)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2384)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at com.google.android.datatransport.runtime.scheduling.persistence.SchemaManager.lambda$static$4(SchemaManager.java:136)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at com.google.android.datatransport.runtime.scheduling.persistence.-$$Lambda$SchemaManager$T1DaSoWWCWfbynOycgGeN7Vw-Vk.upgrade(Unknown Source:0)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at com.google.android.datatransport.runtime.scheduling.persistence.SchemaManager.upgrade(SchemaManager.java:217)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at com.google.android.datatransport.runtime.scheduling.persistence.SchemaManager.onUpgrade(SchemaManager.java:184)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:515)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:413)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at com.google.android.datatransport.runtime.scheduling.persistence.-$$Lambda$iV7-zVaNm3OzwRKNnkXrWOPrqvk.produce(Unknown Source:2)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.retryIfDbLocked(SQLiteEventStore.java:568)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.getDb(SQLiteEventStore.java:94)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(SQLiteEventStore.java:751)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.WorkInitializer.lambda$ensureContextsScheduled$1$WorkInitializer(WorkInitializer.java:54)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.-$$Lambda$WorkInitializer$4euq1WvqLQFGz_1FrH7d8V-ONnE.run(Unknown Source:2)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022.06.01 18:14:58.539 2706 2805 Error TransportRuntime.Executor 	at java.lang.Thread.run(Thread.java:920)

```

#### Steps to reproduce:

It happens every time on applications starts.

**Comment by paulinon** [comment]
Hi @shefich,

It would be more helpful if you provide a minimal, reproducible example of your project along with the complete steps you've taken to replicate the issue. Were you making an AAB build and testing with Google Play Internal Testing distribution when you first encountered this behavior?

Additionally, could you also confirm if the issue persists with just the Firebase SDK in your implementation?
