### ISSUE TITLE
[Bug] App will crash after click push notification on Android

### ISSUE THREAD

**Issue by rayss1** [firebase/firebase-unity-sdk#368]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.32f1c1
  * Firebase Unity SDK version: 9.0.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Messaging
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? 100%

What happened? How can we make the problem occur?
The test phone is Pixel 4 XL, and the system version is Android 11. When receiving a push notification, click the notification, and the App will crash after a short period of time. The crash stack is below:
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH: Version '2020.3.32f1c1 (76260b79758e)', Build type 'Development', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH: Build fingerprint: 'google/coral/coral:11/RP1A.200720.009/6720564:user/release-keys'
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH: Revision: 'MP1.0'
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH: ABI: 'arm64'
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH: Timestamp: 2022-06-24 14:16:39+0800
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH: pid: 12142, tid: 12205, name: Thread-43  >>> sg.partying.ghost.android <<<
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH: uid: 10330
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:     x0  0000000000000000  x1  0000000000002fad  x2  0000000000000006  x3  00000078a010a8b0
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:     x4  0000000000008080  x5  0000000000008080  x6  0000000000008080  x7  0000000000000038
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:     x8  00000000000000f0  x9  480fedd773e8212e  x10 0000000000000000  x11 ffffffc0fffffbdf
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:     x12 0000000000000001  x13 0000044e425643c8  x14 0025f6e7bb3055cd  x15 000000000309f9c6
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:     x16 0000007bb0959c80  x17 0000007bb093b3b0  x18 000000788edd8000  x19 0000000000002f6e
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:     x20 0000000000002fad  x21 00000000ffffffff  x22 00000078b0a3d530  x23 000000788edd5000
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:     x24 000000788edd8000  x25 0000000000000001  x26 00000078a8337ac0  x27 00000000000fc000
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:     x28 00000078a0012000  x29 00000078a010a930
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:     sp  00000078a010a890  lr  0000007bb08eee20  pc  0000007bb08eee4c
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH: backtrace:
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #00 pc 000000000004de4c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 03452a4a418e14ff93948f26561eace6)
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #01 pc 0000000000042910  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::map(void*, unsigned long, char const*, unsigned long, scudo::MapPlatformData*)) (BuildId: 03452a4a418e14ff93948f26561eace6)
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #02 pc 0000000000042f88  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::reportError(char const*)) (BuildId: 03452a4a418e14ff93948f26561eace6)
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #03 pc 0000000000043050  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::reportHeaderRace(void*)) (BuildId: 03452a4a418e14ff93948f26561eace6)
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #04 pc 00000000000445c0  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::Allocator<scudo::AndroidConfig, &(scudo_malloc_postinit)>::deallocate(void*, scudo::Chunk::Origin, unsigned long, unsigned long)+328) (BuildId: 03452a4a418e14ff93948f26561eace6)
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #05 pc 000000000020b4bc  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libFirebaseCppApp-9_0_0.so (firebase::messaging::Notification::~Notification()+48)
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #06 pc 000000000020bb0c  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libFirebaseCppApp-9_0_0.so (firebase::messaging::Message::~Message()+28)
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #07 pc 000000000020babc  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libFirebaseCppApp-9_0_0.so (Firebase_Messaging_CSharp_delete_FirebaseMessage+20)
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #08 pc 00000000022cf3d8  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #09 pc 00000000022cf24c  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #10 pc 00000000022cf114  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #11 pc 000000000074a048  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #12 pc 00000000009df208  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #13 pc 0000000000a35698  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
2022-06-24 14:16:39.643 12142-12205/sg.partying.ghost.android E/CRASH:       #14 pc 0000000000a18940  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
2022-06-24 14:16:39.644 12142-12205/sg.partying.ghost.android E/CRASH:       #15 pc 0000000000a355d0  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
2022-06-24 14:16:39.644 12142-12205/sg.partying.ghost.android E/CRASH:       #16 pc 00000000009ae808  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
2022-06-24 14:16:39.644 12142-12205/sg.partying.ghost.android E/CRASH:       #17 pc 00000000009ad0e4  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
2022-06-24 14:16:39.644 12142-12205/sg.partying.ghost.android E/CRASH:       #18 pc 00000000000af888  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 03452a4a418e14ff93948f26561eace6)
2022-06-24 14:16:39.644 12142-12205/sg.partying.ghost.android E/CRASH:       #19 pc 000000000004fe08  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 03452a4a418e14ff93948f26561eace6)
2022-06-24 14:16:39.782 12142-12199/sg.partying.ghost.android E/CRASH: other thread is trapped; signum = 6
2022-06-24 14:16:39.783 12142-12199/sg.partying.ghost.android E/AndroidRuntime: FATAL EXCEPTION: UnityMain
    Process: sg.partying.ghost.android, PID: 12142
    java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Version '2020.3.32f1c1 (76260b79758e)', Build type 'Development', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
    Build fingerprint: 'google/coral/coral:11/RP1A.200720.009/6720564:user/release-keys'
    Revision: 'MP1.0'
    ABI: 'arm64'
    Timestamp: 2022-06-24 14:16:39+0800
    pid: 12142, tid: 12205, name: Thread-43  >>> sg.partying.ghost.android <<<
    uid: 10330
    signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
        x0  0000000000000000  x1  0000000000002fad  x2  0000000000000006  x3  00000078a010a8b0
        x4  0000000000008080  x5  0000000000008080  x6  0000000000008080  x7  0000000000000038
        x8  00000000000000f0  x9  480fedd773e8212e  x10 0000000000000000  x11 ffffffc0fffffbdf
        x12 0000000000000001  x13 0000044e425643c8  x14 0025f6e7bb3055cd  x15 000000000309f9c6
        x16 0000007bb0959c80  x17 0000007bb093b3b0  x18 000000788edd8000  x19 0000000000002f6e
        x20 0000000000002fad  x21 00000000ffffffff  x22 00000078b0a3d530  x23 000000788edd5000
        x24 000000788edd8000  x25 0000000000000001  x26 00000078a8337ac0  x27 00000000000fc000
        x28 00000078a0012000  x29 00000078a010a930
        sp  00000078a010a890  lr  0000007bb08eee20  pc  0000007bb08eee4c
    
    backtrace:
          #00 pc 000000000004de4c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 03452a4a418e14ff93948f26561eace6)
          #01 pc 0000000000042910  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::map(void*, unsigned long, char const*, unsigned long, scudo::MapPlatformData*)) (BuildId: 03452a4a418e14ff93948f26561eace6)
          #02 pc 0000000000042f88  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::reportError(char const*)) (BuildId: 03452a4a418e14ff93948f26561eace6)
          #03 pc 0000000000043050  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::reportHeaderRace(void*)) (BuildId: 03452a4a418e14ff93948f26561eace6)
          #04 pc 00000000000445c0  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::Allocator<scudo::AndroidConfig, &(scudo_malloc_postinit)>::deallocate(void*, scudo::Chunk::Origin, unsigned long, unsigned long)+328) (BuildId: 03452a4a418e14ff93948f26561eace6)
          #05 pc 000000000020b4bc  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libFirebaseCppApp-9_0_0.so (firebase::messaging::Notification::~Notification()+48)
          #06 pc 000000000020bb0c  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libFirebaseCppApp-9_0_0.so (firebase::messaging::Message::~Message()+28)
          #07 pc 000000000020babc  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libFirebaseCppApp-9_0_0.so (Firebase_Messaging_CSharp_delete_FirebaseMessage+20)
          #08 pc 00000000022cf3d8  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
          #09 pc 00000000022cf24c  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
          #10 pc 00000000022cf114  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
          #11 pc 000000000074a048  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
          #12 pc 00000000009df208  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
2022-06-24 14:16:39.783 12142-12199/sg.partying.ghost.android E/AndroidRuntime:       #13 pc 0000000000a35698  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
          #14 pc 0000000000a18940  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
          #15 pc 0000000000a355d0  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
          #16 pc 00000000009ae808  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
          #17 pc 00000000009ad0e4  /data/app/~~cUX5Y9ITCVNdwo-wGHSSkQ==/sg.partying.ghost.android-RxqRkQLvO64dyg6F_gparA==/lib/arm64/libil2cpp.so (BuildId: 6912c830d60ced2c28d57160feebd00fe040a0ce)
          #18 pc 00000000000af888  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 03452a4a418e14ff93948f26561eace6)
          #19 pc 000000000004fe08  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 03452a4a418e14ff93948f26561eace6)
    
        at libc.abort(abort:164)
        at libc.scudo::map(void*, unsigned long, char const*, unsigned long, scudo::MapPlatformData*)(map:0)
        at libc.scudo::reportError(char const*)(reportError:0)
        at libc.scudo::reportHeaderRace(void*)(reportHeaderRace:0)
        at libc.scudo::Allocator<scudo::AndroidConfig, &(scudo_malloc_postinit)>::deallocate(void*, scudo::Chunk::Origin, unsigned long, unsigned long)(AndroidConfig, &:328)
        at libFirebaseCppApp-9_0_0.firebase::messaging::Notification::~Notification()(~Notification:48)
        at libFirebaseCppApp-9_0_0.firebase::messaging::Message::~Message()(~Message:28)
        at libFirebaseCppApp-9_0_0.Firebase_Messaging_CSharp_delete_FirebaseMessage(Firebase_Messaging_CSharp_delete_FirebaseMessage:20)
        at libil2cpp.0x22cf3d8(Native Method)
        at libil2cpp.0x22cf24c(Native Method)
        at libil2cpp.0x22cf114(Native Method)
        at libil2cpp.0x74a048(Native Method)
        at libil2cpp.0x9df208(Native Method)
        at libil2cpp.0xa35698(Native Method)
        at libil2cpp.0xa18940(Native Method)
        at libil2cpp.0xa355d0(Native Method)
        at libil2cpp.0x9ae808(Native Method)
        at libil2cpp.0x9ad0e4(Native Method)
        at libc.__pthread_start(void*)(__pthread_start:64)
        at libc.__start_thread(__start_thread:64)
2022-06-24 14:16:39.783 12142-12199/sg.partying.ghost.android E/CrashReport: Java Crash Happen cause by UnityMain(6071)

My code here:

public class FirebaseMgr
{
    private static readonly FirebaseMgr instance = new FirebaseMgr();

    static FirebaseMgr(){}

    private FirebaseMgr(){}

    public static FirebaseMgr Instance
    {
        get
        {
            return instance;
        }
    }

    private Firebase.FirebaseApp app;
    private bool isReady = false;
    private string token = null;

    public bool IsReady
    {
        get { return isReady; }
    }

    public bool IsTokenReady
    {
        get { return token != null; }
    }

    public void Init()
    {
        UnityEngine.Debug.Log("Firebase.FirebaseApp Init called!");
        Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
            var dependencyStatus = task.Result;
            if (dependencyStatus == Firebase.DependencyStatus.Available) {
                // Create and hold a reference to your FirebaseApp,
                // where app is a Firebase.FirebaseApp property of your application class.
                app = Firebase.FirebaseApp.DefaultInstance;

                // Set a flag here to indicate whether Firebase is ready to use by your app.
                isReady = true;

                UnityEngine.Debug.Log("Firebase.FirebaseApp is ready");

                Firebase.Messaging.FirebaseMessaging.TokenReceived += OnTokenReceived;
                Firebase.Messaging.FirebaseMessaging.MessageReceived += OnMessageReceived;

                GetTokenAsync();
            } else {
                UnityEngine.Debug.LogError(System.String.Format(
                "Could not resolve all Firebase dependencies: {0}", dependencyStatus));
                // Firebase Unity SDK is not safe to use here.
            }
        });
    }

    public void OnTokenReceived(object sender, Firebase.Messaging.TokenReceivedEventArgs token) {
        UnityEngine.Debug.Log("Received Registration Token: " + token.Token);
        this.token = token.Token;
    }

    public void OnMessageReceived(object sender, Firebase.Messaging.MessageReceivedEventArgs e)
    {
        UnityEngine.Debug.Log("Received a new message from: " + e.Message.From);
        UnityEngine.Debug.Log("Message Id: " + e.Message.MessageId);
        UnityEngine.Debug.Log("Message Type: " + e.Message.MessageType);
        UnityEngine.Debug.Log("Notification Title: " + e.Message.Notification.Title);
        UnityEngine.Debug.Log("Notification Body: " + e.Message.Notification.Body);
    }

    private async void GetTokenAsync()
    {
        var task = Firebase.Messaging.FirebaseMessaging.GetTokenAsync();
    
        await task;
    
        if (task.IsCompleted)
        {
            Debug.Log("Received Registration Token: "+ task.Result);
            this.token = task.Result;
        }
    }

    public string GetToken()
    {
        return this.token;
    }
}

**Comment by paulinon** [comment]
Hi @rayss1,

Thanks for reporting this to us. While I try to reproduce this issue, could you verify if the behavior persists using version 9.1.0 of the SDK?
