### ISSUE TITLE
CheckAndFixDependenciesAsync causes ANR [Bug] 

### ISSUE THREAD

**Issue by yakirbu** [firebase/firebase-unity-sdk#407]
* Unity editor version: 2021.3.5f1
  * Firebase Unity SDK version: Tested with 9.0.0, 9.1.0 and 9.2.0
  * Source you installed the SDK: Unity Package Manager (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: FirebaseApp (Auth, Database, etc.)
  * Other Firebase Components in use: I use all except 'Cloud Firestore' (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, Admob and many more (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac and Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

Very often 'FirebaseApp.CheckAndFixDependenciesAsync' function does not complete its execution when running the game on Android phones, hence, no response is given at all, and after a minute or two, it causes APR/Crash.

Extra note: We tested the same build many times in 2 different Android phones (Samsung S22 Ultra and Samsung Note 9), and it seems to occur much more often in the Note 9 than in the S22 Ultra.   

**One more important thing to mention**
Adding the line: "FirebaseApp.LogLevel = LogLevel.Debug;" before calling 'CheckAndFixDependenciesAsync', solves the issue, but as you probably assume, we don't want to leave it that way.

#### Relevant Code:

```
FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task => {
               *** The app hangs and never reach this area ***
                var dependencyStatus = task.Result;
                if (dependencyStatus == Firebase.DependencyStatus.Available) 
                {
                    InitializeFirebaseComponents();
                } 
                else 
                {
                    Debug.LogError($"Could not resolve all Firebase dependencies: {dependencyStatus}");
                }
            });

```

**ANR Log (From Firebase Crashlytics):**

![ANR log](https://user-images.githubusercontent.com/12374325/179465200-413bcfb3-eef0-49ed-92dd-4a8c222eafb0.jpg)

**Same log but in text:**
```
main (native): tid=1 systid=9129 
#00 pc 0xa289c libc.so 
#01 pc 0x144131c libil2cpp.so 
#02 pc 0x1456c88 libil2cpp.so 
#03 pc 0x15d13f0 libil2cpp.so 
#04 pc 0x155b204 libil2cpp.so 
#05 pc 0x1624db0 libil2cpp.so 
#06 pc 0x3ae308 libunity.so 
#07 pc 0x145048 libunity.so 
#08 pc 0x144f60 libunity.so 
#09 pc 0x2d4044 libart.so 
#10 pc 0x2ca9e8 libart.so 
#11 pc 0x2ee6b8 libart.so 
#12 pc 0x40ade4 libart.so 
#13 pc 0x76d4b8 libart.so 
#14 pc 0x2c5014 libart.so 
#15 pc 0x4f304c base.apk 
#16 pc 0x76ce1c libart.so 
#17 pc 0x2c5014 libart.so 
#18 pc 0x4f2aca base.apk 
#19 pc 0x27d840 libart.so 
#20 pc 0x35a9e4 libart.so 
#21 pc 0x40b05c libart.so 
#22 pc 0x3d537c libart.so 
#23 pc 0x2c5094 libart.so 
#24 pc 0xfd51c core-oj.jar 
#25 pc 0x27d840 libart.so 
#26 pc 0x27c9e8 libart.so 
#27 pc 0x2d4178 libart.so 
#28 pc 0x2ca9e8 libart.so 
#29 pc 0x3655bc libart.so 
#30 pc 0x5fddfc libart.so 
#31 pc 0x570e94 libart.so 
#32 pc 0x3a2828 libart.so 
#33 pc 0x3a1534 libart.so 
#34 pc 0x2d3c5c libart.so 
#35 pc 0x2ca764 libart.so 
#36 pc 0x2ee6b0 libart.so 
#37 pc 0x40ade4 libart.so 
#38 pc 0x3d537c libart.so 
#39 pc 0x2c5094 libart.so 
#40 pc 0x2c8ac4 base.apk 
#41 pc 0x27d840 libart.so 
#42 pc 0x35a9e4 libart.so 
#43 pc 0x40b05c libart.so 
#44 pc 0x2c0ea4 libart.so 
#45 pc 0x2c4e94 libart.so 
#46 pc 0x206070 base.apk 
#47 pc 0x27d840 libart.so 
#48 pc 0x35a9e4 libart.so 
#49 pc 0x40b05c libart.so 
#50 pc 0x2c0ea4 libart.so 
#51 pc 0x2c4e94 libart.so 
#52 pc 0x1cb322 base.apk 
#53 pc 0x27d840 libart.so 
#54 pc 0x35a9e4 libart.so 
#55 pc 0x40b05c libart.so 
#56 pc 0x2c0ea4 libart.so 
#57 pc 0x2c4e94 libart.so 
#58 pc 0x47bb28 framework.jar 
#59 pc 0x3d4368 libart.so 
#60 pc 0x2c5094 libart.so 
#61 pc 0x11063e dl-AdsFdrDynamite.integ_221908400100000.apk 
#62 pc 0x27d840 libart.so 
#63 pc 0x2ede78 libart.so 
#64 pc 0x2c0fbc libart.so 
#65 pc 0x2c4e94 libart.so 
#66 pc 0x15ac40 dl-AdsFdrDynamite.integ_221908400100000.apk 
#67 pc 0x27d840 libart.so 
#68 pc 0x2ede78 libart.so 
#69 pc 0x3d544c libart.so 
#70 pc 0x2c5094 libart.so 
#71 pc 0x1b512c dl-AdsFdrDynamite.integ_221908400100000.apk 
#72 pc 0x27d840 libart.so 
#73 pc 0x35a9e4 libart.so 
#74 pc 0x40b05c libart.so 
#75 pc 0x3d537c libart.so 
#76 pc 0x2c5094 libart.so 
#77 pc 0x48daa4 framework.jar 
#78 pc 0x76ce1c libart.so 
#79 pc 0x2c5014 libart.so 
#80 pc 0x48d918 framework.jar 
#81 pc 0x2ebc84 libart.so 
#82 pc 0x2c4f14 libart.so 
#83 pc 0x201570 dl-AdsFdrDynamite.integ_221908400100000.apk 
#84 pc 0x27d840 libart.so 
#85 pc 0x2ede78 libart.so 
#86 pc 0x2eba44 libart.so 
#87 pc 0x2c4f14 libart.so 
#88 pc 0x165a22 dl-AdsFdrDynamite.integ_221908400100000.apk 
#89 pc 0x27d840 libart.so 
#90 pc 0x2ede78 libart.so 
#91 pc 0x2c0fbc libart.so 
#92 pc 0x2c4e94 libart.so 
#93 pc 0x201558 dl-AdsFdrDynamite.integ_221908400100000.apk 
#94 pc 0x27d840 libart.so 
#95 pc 0x27c9e8 libart.so 
#96 pc 0x2d4178 libart.so 
#97 pc 0x202aa54 memfd:jit-cache 
#98 pc 0x2ca9e8 libart.so 
#99 pc 0x2ee6b8 libart.so 
#0100 pc 0x40ade4 libart.so 
#0101 pc 0x76d4b8 libart.so 
#0102 pc 0x2c5014 libart.so 
#0103 pc 0x4cb3e8 framework.jar 
#0104 pc 0x76c840 libart.so 
#0105 pc 0x2c5014 libart.so 
#0106 pc 0x1bcb9e framework.jar 
#0107 pc 0x27d840 libart.so 
#0108 pc 0x27c9e8 libart.so 
#0109 pc 0x2d4178 libart.so 
#0110 pc 0x2ca9e8 libart.so 
#0111 pc 0x35b5d0 libart.so 
#0112 pc 0x35b348 libart.so 
       at com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native method)
       at com.unity3d.player.ReflectionHelper.a(unavailable)
       at com.unity3d.player.ReflectionHelper$1.invoke(unavailable)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at com.google.android.gms.ads.initialization.OnInitializationCompleteListener.onInitializationComplete(com.google.android.gms:play-services-ads-lite@@21.0.0)
       at com.google.android.gms.ads.internal.client.zzed.zzb(com.google.android.gms:play-services-ads-lite@@21.0.0:5)
       at com.google.android.gms.internal.ads.zzbql.zzbI(com.google.android.gms:play-services-ads-lite@@21.0.0:3)
       at com.google.android.gms.internal.ads.zzaqw.onTransact(com.google.android.gms:play-services-ads-base@@21.0.0:3)
       at android.os.Binder.transact(Binder.java:1100)
       at ady.be(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:2)
       at com.google.android.gms.ads.internal.initialization.f.e(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857)
       at com.google.android.gms.ads.nonagon.initialization.f.run(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at arc.a(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857)
       at com.google.android.gms.ads.internal.util.f.a(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:1)
       at arc.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

**Comment by paulinon** [comment]
Hi @yakirbu,

In order to identify what's causing this, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the complete steps to replicate your issue?
