### ISSUE TITLE
[Bug]  Firebase Messaging produce an app to crash on Android, Unity2023+ 

### ISSUE THREAD

**Issue by streaminspace** [firebase/firebase-unity-sdk#640]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: all 2023
  * Firebase Unity SDK version: 10.5.0
  * Source you installed the SDK: .unitypackage and Unity Package Manager
  * Problematic Firebase Component: Messaging
  * Other Firebase Components in use:  no
  * Additional SDKs you are using: no
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: website
### [REQUIRED] Please describe the issue here:
If the application uses the Firebase Messaging component it crashes immediately after launching. 
Can be reproduced only on unity 2023 versions

As I understand this is a known issue and probably [this pull request](https://github.com/firebase/firebase-unity-sdk/pull/626) is a solution,  but I faced errors during the build components from open-source from this repo and can not test it
#### Steps to reproduce:

1. Create a new unity project. 
2. Import the FirebaseMessaging package.
3. Make an android build and run it.
4. App crashes immediately 

Log:
`Fatal Exception: java.lang.NoSuchFieldError: No instance field mUnityPlayer of type Lcom/unity3d/player/UnityPlayer; in class Lcom/google/firebase/MessagingUnityPlayerActivity; or its superclasses (declaration of 'com.google.firebase.MessagingUnityPlayerActivity' appears in /data/app/~~g6VuJKtoISkXfbapr-BX3g==/com.nanorealitygames.mynanoworldreborn-nyp7vD0cKtiD6u26nQn-mw==/base.apk)
       at com.google.firebase.MessagingUnityPlayerActivity.onCreate(MessagingUnityPlayerActivity.java:87)
       at android.app.Activity.performCreate(Activity.java:8578)
       at android.app.Activity.performCreate(Activity.java:8557)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4147)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4312)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

**Comment by a-maurice** [comment]
Hi @streaminspace 

Unity 2023 introduced a couple of changes that cause some problems with the Firebase Unity SDK.  The issue you are seeing here is in the UnityPlayerActivity class; the type of mUnityPlayer for 2023 has changed.  The PR that you linked against addressing this issue specifically, and will be included in the next release.

If you want to try a workaround, something that might work (though I'm not 100% sure):
1. Copy https://github.com/firebase/firebase-unity-sdk/blob/main/messaging/activity/com/google/firebase/MessagingUnityPlayerActivity.java locally
2. Rename that file to something like MessagingUnityPlayerActivity2.java
3. Adjust the class name within that file to the same thing you renamed it to
4. In your project, under Assets/Plugins/Android, there should be an AndroidManifest.xml file.  Within that, change the MessagingUnityPlayerActivity mention to use your new named class.

That should theoretically tell it to use the Activity that it does have the source code for, and thus mUnityPlayer will be resolved correctly.  My one concern with this would be if it can resolve the dependencies correctly.

Other issues will arise if you try to use the new GameActivity functionality, both in Messaging itself, but also in the External Dependency Manager, which is the tool we use to help manage Android and iOS dependencies.  We are still working on addressing those issues.

**Comment by streaminspace** [comment]
Hello @a-maurice !

Thank you for your answer, this helped me! Finally, I was able to launch a build without crashing

**Comment by DellaBitta** [comment]
Great news! I'm going to close this issue for now. If you run into any related issues please open a new ticket and link this one to it. Thanks!
