### ISSUE TITLE
[Bug] generate_xml_from_google_services_json.exe: Unexpected token '-i' in expression or statement

### ISSUE THREAD

**Issue by nmtoan91** [firebase/firebase-unity-sdk#835]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3
  * Firebase Unity SDK version: 11.3.0
  * Source you installed the SDK: FirebaseAnalytics(.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Analytics(Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: AdMob(Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows(Mac, Windows, or Linux)
  * Platform you are targeting: Android(iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP(Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:
I just follow the instruction, I also create a realtime-database.
The error popup when I open the unity project:

Here is the log:
```
Generation of the Firebase Android resource file google-services.xml from Assets/google-services.json failed.
If you have not included a valid Firebase Android resources in your app it will fail to initialize.

"F:\MUZIVERSE\2023_01_07_BEACHWAR\BeachWar\Assets\Firebase\Editor\generate_xml_from_google_services_json.exe" -i "Assets/google-services.json" -l

Traceback (most recent call last):
  File "C:\dev\firebase-cpp-sdk\generate_xml_from_google_services_json.py", line 498, in <module>
  File "C:\dev\firebase-cpp-sdk\generate_xml_from_google_services_json.py", line 365, in main
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 6 column 2 (char 174)
[28924] Failed to execute script 'generate_xml_from_google_services_json' due to unhandled exception!



You can start to diagnose this issue by executing ""F:\MUZIVERSE\2023_01_07_BEACHWAR\BeachWar\Assets\Firebase\Editor\generate_xml_from_google_services_json.exe" -i "Assets/google-services.json" -l" from the command line.
UnityEngine.Debug:LogError (object)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:RunResourceGenerator (System.Collections.Generic.IEnumerable`1<string>,string,bool) (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/editor/app/src/GenerateXmlFromGoogleServicesJson.cs:545)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:ReadBundleIds (string) (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/editor/app/src/GenerateXmlFromGoogleServicesJson.cs:409)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:UpdateConfigFileDirectory () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/editor/app/src/GenerateXmlFromGoogleServicesJson.cs:297)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:CheckConfiguration () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/editor/app/src/GenerateXmlFromGoogleServicesJson.cs:248)
Firebase.Editor.GenerateXmlFromGoogleServicesJson/<>c:<.cctor>b__15_1 () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/editor/app/src/GenerateXmlFromGoogleServicesJson.cs:103)
Google.EditorInitializer/<InitializeOnMainThread>c__AnonStorey1:<>m__2 () (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/VersionHandlerImpl/src/EditorInitializer.cs:60)
Google.RunOnMainThread:ExecutePollingJobs () (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409)
Google.RunOnMainThread:<ExecuteAllUnnested>m__12 () (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction (System.Action) (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested (bool) (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:ExecuteAll () (at /Users/chkuang/Workspace/git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:512)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```

Here is the log when I run the command manually:
```
At line:1 char:111
+ ... irebase\Editor\generate_xml_from_google_services_json.exe" -i "Assets ...
+                                                                ~~
Unexpected token '-i' in expression or statement.
At line:1 char:114
+ ... ml_from_google_services_json.exe" -i "Assets/google-services.json" -l
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token '"Assets/google-services.json"' in expression or statement.
At line:1 char:144
+ ... ml_from_google_services_json.exe" -i "Assets/google-services.json" -l
+                                                                        ~~
Unexpected token '-l' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

**Comment by paulinon** [comment]
Hi @nmtoan91,

Thanks for bringing this to our attention. Could you try if this [solution](https://github.com/firebase/quickstart-unity/issues/946#issuecomment-774337225) or using a new `google-services.json` file makes any difference? If not, please provide the complete steps you've taken before facing this issue so that we can identify what's causing this behavior.
