### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by johntitor08** [firebase/firebase-unity-sdk#853]
Build completed with a result of 'Failed' in 66 seconds (65667 ms)
Building Library\Bee\artifacts\WebGL\ManagedStripped failed with output:
C:\Program Files\Unity\Hub\Editor\2022.3.5f1\Editor\Data\il2cpp\build\deploy\UnityLinker.exe @Library\Bee\artifacts\rsp\14219894640897552874.rsp
Fatal error in Unity CIL Linker
Mono.Linker.LinkerFatalErrorException: /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/database/src/internal/InternalValueListener.cs(16707566): error IL1005: Firebase.Database.Internal.InternalValueListener.OnCancelledHandler(Int32,Error,String): Error processing method 'Firebase.Database.Internal.InternalValueListener.OnCancelledHandler(Int32,Error,String)' in assembly 'Firebase.Database.dll'
 ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Firebase.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Unity.IL2CPP.Common.MissingMethodStubber.GetTypeModule(TypeReference type, IEnumerable`1 assemblies)
   at Unity.Linker.Steps.AddUnresolvedStubsStep.MarkAssemblyOfType(UnityLinkContext context, TypeReference type)
   at Unity.Linker.Steps.Marking.UnresolvedStubMarking.HandleUnresolvedType(TypeReference reference)
   at Unity.Linker.Steps.Marking.UnresolvedStubMarking.HandleUnresolvedMethod(MethodReference reference)
   at Unity.Linker.Steps.UnityMarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction, MethodDefinition method, Boolean& requiresReflectionMethodBodyScanner)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Unity.Linker.Steps.UnityMarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
   at Unity.Linker.Steps.UnityMarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Unity.Linker.Steps.UnityMarkStep.Process(LinkContext context)
   at Unity.Linker.UnityPipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Unity.Linker.UnityDriver.UnityRun(UnityLinkContext context, UnityPipeline p, LinkRequest linkerOptions, TinyProfiler2 tinyProfiler, ILogger customLogger)
   at Unity.Linker.UnityDriver.RunDriverWithoutErrorHandling(TinyProfiler2 tinyProfiler, ILogger customLogger)
   at Unity.Linker.UnityDriver.RunDriverWithoutErrorHandling()
   at Unity.Linker.UnityDriver.RunDriver()

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun ()

**Comment by argzdev** [comment]
Hi again, @johntitor08. Like I mentioned in #854, while a stacktrace does show us the error. It's not enough detail for us to conduct an initial investigation. That said, could you file a new issue with the necessary details from our template? It'll help us in finding a resolution a lot better. Thanks!
